### ISSUE TITLE
Schema.org PaymentMethod as namespace for short strings

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments-method-identifiers#13]
Since we resolved to use short-strings for payment method identifiers that are not minted by independent entities does it make sense for us to register these short strings (or re-use those) in the http://purl.org/goodrelations/v1 namespace.

See http://schema.org/PaymentMethod

This also begs the question of whether it makes sense for the payment method manifest to have a well defined context and use this Schema.org type?

**Comment by adrianba** [comment]
The reason we decided to go with short-strings was to avoid any overhead from having to manage an external registry. It doesn't make sense to me to now decide to use an external registry for these strings. How about we just define the strings in the payment method specs?

**Comment by ianbjacobs** [comment]
I would put it slightly differently:
- It seems we can advance the specification without needing a registry (beyond the definition in the spec).
- It may be useful independently to register the strings in one more more registrations. (And more investigation would need to happen to determine there's a value in doing so.)

I would not hold up the spec for a registry.

Ian

**Comment by adrianhopebailie** [comment]
> It seems we can advance the specification without needing a registry (beyond the definition in the spec).
> It may be useful independently to register the strings in one more more registrations. (And more investigation would need to happen to determine there's a value in doing so.)

+1 , but I will add that we have ignored, up to now that there is already a registry that we COULD just use where the short-strings are implied to be the fragments on a http://purl.org/goodrelations/v1 base URL ...
- http://purl.org/goodrelations/v1#VISA
- http://purl.org/goodrelations/v1#ByInvoice
- http://purl.org/goodrelations/v1#COD

**Comment by adrianba** [comment]
> I will add that we have ignored, up to now that there is already a registry that we COULD just use 

I don't believe that is true. There are many registries we _could_ just use. I don't believe we need one and I recommend closing this issue.

**Comment by ianbjacobs** [comment]
Closing this issue based on discussion above and also group resolution (cf the PMI spec [1]) that "W3C identifies these payment methods with (short) strings; W3C expects to mint these strings in payment method specifications published by the Web Payments Working Group.".

We can always do more if we perceive that it would be useful.

[1] https://www.w3.org/TR/payment-method-id/#w3c-defined-strings-as-payment-method-identifiers
