### ISSUE TITLE
Why are payment ids restricted to [a-z0-9]?

### ISSUE THREAD

**Issue by stevenatkin** [w3c/webpayments-method-identifiers#20]
4.1 Syntax
https://w3c.github.io/webpayments-method-identifiers/#syntax-1

Is there a specific requirement that identifiers be restricted to [a-z0-9-]? Are there any international card issuers that may require characters outside this range?

**Comment by ianbjacobs** [comment]
Hi Steve,

I'm not aware that we've encountered any.

Also, these strings are intended for automated matching and so are not intended for humans to read. They will most likely never be seen by users.

Ian

**Comment by marcoscaceres** [comment]
This seems wrong for URLs. There are effectively two types:

 * URLs, which are USVString
 * Predefined enum values (e.g., "basic-card") 

We should make sure the spec reflects this properly.
