### ISSUE TITLE
Circular dependency between PMI and PR specs

### ISSUE THREAD

**Issue by adrianhopebailie** [w3c/webpayments-method-identifiers#22]
The PMI spec lists the Payment Request spec as a normative dependency and the Payment Request spec lists this spec as a normative dependency.

**Comment by marcoscaceres** [comment]
I think that fine. They just progress together. At the end of the day, it's humans that decide how the specs progress along the REC track, and we can just make exceptions for things like this.

**Comment by adrianba** [comment]
The original design was that PMI should be usable without PaymentRequest so it should be informative at most.
