### ISSUE TITLE
citation to dated version of since-abandoned url spec fork is unusual

### ISSUE THREAD

**Issue by dbaron** [w3c/webpayments-method-identifiers#30]
The [References section](https://w3c.github.io/webpayments-method-identifiers/#references) currently cites a dated version of a spec:
>[url-1-20141209]
>    URL. Anne van Kesteren; Sam Ruby. W3C. 9 December 2014. W3C Working Draft. URL: https://www.w3.org/TR/2014/WD-url-1-20141209/ 

whose "Latest version" link leads to https://www.w3.org/TR/2016/NOTE-url-1-20161206/, which says:

> Work on this document has been discontinued and it **should not be referenced** or used as a basis for implementation. Please refer to the URL Continually Updated Specification for the latest available specification of this API.

(emphasis mine).

Given this state of the document, it seems odd that Payment Method Identifiers references it.

(I got here from w3ctag/spec-reviews#152.)

**Comment by marcoscaceres** [comment]
Oh, thank goodness (well, thank Annevk) they gave up on the URL spec. Will update the reference... now, can we get the same for DOM and HTML? 🤓

**Comment by ianbjacobs** [comment]
I believe that we can refer to WhatWG specs that have material not present in W3C versions.

**Comment by zkoch** [comment]
Assigning to Marcos because he said: "Will update the reference"

Also he didn't object in the meeting ;)
