### ISSUE TITLE
Remove "Conditional Matching Beyond Payment Method Identifier Matching"

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webpayments-method-identifiers#34]
The section "Conditional Matching Beyond Payment Method Identifier Matching" is out of place in this specification. We should move that to a "best practices" wiki page or something.

**Comment by ianbjacobs** [comment]
We have a candidate document where this could go (e.g., in section 3.1):

Payment Method Best Practice
https://w3c.github.io/webpayments/proposals/method-practice/

**Comment by marcoscaceres** [comment]
Excellent!
