### ISSUE TITLE
Rename repo payment-method-id

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webpayments-method-identifiers#38]
The repo should be renamed to match the TR short name.

**Comment by ianbjacobs** [comment]
Hi @marcoscaceres,

Is that something you would like me to do, and if so, when?

(Some links will break; in particular:
 https://w3c.github.io/webpayments-methods-tokenization/ )

Ian

**Comment by marcoscaceres** [comment]
I'm happy to do it, but yeah... we will need to hunt down broken links.

**Comment by marcoscaceres** [comment]
Tokenization spec shouldn't break, as it's pointing to `/TR/`

**Comment by marcoscaceres** [comment]
Done rename, updated links.

**Comment by ianbjacobs** [comment]
Hi Marcos,

Some links to fix:

 * In the spec in the status section, there is " Please file any issues with this specification in the payment method identifiers repository on GitHub." that is now a broken link and should be https://github.com/w3c/payment-method-id/issues

 * Please update in the spec similarly: 
     github: "https://github.com/w3c/webpayments-method-identifiers"

Thanks!

Ian

**Comment by marcoscaceres** [comment]
Thanks, fixing now.
