### ISSUE TITLE
Auto-publishing failing on bad token

### ISSUE THREAD

**Issue by marcoscaceres** [w3c/webpayments-method-identifiers#43]
@ianbjacobs or @sideshowbarker, could you get us a new auto-publish Echidna token for this specification?  

https://github.com/w3c/echidna/wiki/Token-creation

The token we have appears to be invalid (probably copy/pasta from another repo). 

See:
https://lists.w3.org/Archives/Public/public-tr-notifications/2017Jul/0047.html

**Comment by deniak** [comment]
That's because the source of the manifest was [changed](https://github.com/w3c/payment-method-id/commit/87d5ced862f684b7f12463db8486f05a15c1d136#diff-354f30a63fb0907d4ad57269548329e3). I updated the token we have with the new source. It should be better now.

**Comment by marcoscaceres** [comment]
@deniak, thanks! We also just renamed another repo: https://github.com/w3c/payment-request/pull/564#event-1176174814

Cab you please fix that one too?

**Comment by deniak** [comment]
@marcoscaceres done!

**Comment by marcoscaceres** [comment]
Thanks again! 🙇
