### ISSUE TITLE
w3c.github.io/payment-method-id/ is not in parity with the tests

### ISSUE THREAD

**Issue by mhahmadi** [w3c/webpayments-method-identifiers#46]
https://w3c.github.io/payment-method-id/ mentions the following invalid method identifiers are all ignored by the user agent. Some user agents might inform developers that identifiers are invalid to help them fix issues.
const invalid = [
  {
    // ❌ Contains Unicode character outside the valid ranges.
    supportedMethods: "basic-💳",
  },
  {
    // ❌ Contains uppercase characters.
    supportedMethods: "Basic-Card",
  },
  {
    // ❌ Contains Unicode characters outside the valid ranges.
    supportedMethods: "¡basic-*-card!",
  },
];

However the following test expects a RangeError to be thrown when such PMIs are encountered.
https://w3c-test.org/payment-request/payment-request-ctor-pmi-handling.https.html

@marcoscaceres, which one is to be trusted?

**Comment by marcoscaceres** [comment]
Trust the tests. I'll update the spec tomorrow.

**Comment by marcoscaceres** [comment]
Actually, re-reading, I think I removed the "ignore invalid ones" already. Can you point me to the section where it says a user agent must ignore invalid PMIs? Did I miss it?

**Comment by rsolomakhin** [comment]
See the second note in https://w3c.github.io/payment-method-id/#validity-0

**Comment by mhahmadi** [comment]
![screenshot](https://user-images.githubusercontent.com/1598371/29620727-b8bb85c6-87ec-11e7-8d0a-02f6fb359e6a.png)

**Comment by marcoscaceres** [comment]
Thanks! Heh, I've been looking at specs for so long my brain automatically skips over non-normative notes 🙃

**Comment by mhahmadi** [comment]
Thank you for the quick turnaround Marcos.
